### PR TITLE
EdgeImpulse DRPAI Deployment to GStreamer DRPAI plugin translator

### PR DESCRIPTION
**Pull request by matinlotfali**
Read the `README.md`

### CODE REVIEW

**Review by mistyron — COMMENTED** [review]
One thing that I have repeatedly realised in your sources is, that you don't use any inline comments. I think they're helpful to document what a certain function or section of code is about. I think it's something you should get used to to avoid the need to go back into your code to document everything as we all know, that rarely happens. My recommendation is to add comments as you go.

**Review by mistyron — APPROVED** [review]
LGTM - please see my comments, i'm open to discussion!

**Comment by mistyron** [comment]
> Read the `README.md`

That's lazy and repetiive :), can you  provide a quick concise summary of the changes ( you've referred to the `REAME.md` in previous PRs already, right?)

**Comment by matinlotfali** [comment]
> you've referred to the `REAME.md` in previous PRs already, right?)

It is the previous PR but I didn't merge it because it lacked documentation. I added docstrings and comments as requested.
I guess you thought it is another PR that looks very similar to what you have seen before? :-D

**Comment by mistyron** [comment]
> > you've referred to the `REAME.md` in previous PRs already, right?)
> 
> It is the previous PR but I didn't merge it because it lacked documentation. I added docstrings and comments as requested. I guess you thought it is another PR that looks very similar to what you have seen before? :-D

Oh, yeah,  I see :)

**Review by mistyron — APPROVED** [review]
LGTM Thanks for adding the comments!

**Pull request merged**
